version: '3.8'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
